"""add address relation

Revision ID: 25ba6ed7e31a
Revises: 3b1bacede7e7
Create Date: 2025-02-14 08:03:09.664510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ba6ed7e31a'
down_revision: Union[str, None] = '3b1bacede7e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('owner_address', sa.String(), nullable=False))
    op.add_column('sessions', sa.Column('chat_history', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'chat_history')
    op.drop_column('models', 'owner_address')
    # ### end Alembic commands ###
